### ISSUE TITLE
Pregunta sobre este repositorio y materia

### ISSUE THREAD

**Issue by FavioVazquez** [dpsanders/fisica_computacional#1]
Hola mucho gusto Dr. Sanders, soy un estudiante de la maestría de ciencias físicas de la UNAM, y me interesaba ver una materia con usted pero vi que no ofrecía ninguna este semestre. ¿Esta materia está abierta para el semestre 2016-I? Porque no está listada en la página de los cursos.

Saludos. Mi nombre es Favio Vázquez. Soy de Venezuela.

**Comment by dpsanders** [comment]
Hola,

Gracias por tu interés. Este curso es de la licenciatura, así que no lo
podrás tomar para crédito. Si te interesa tomarlo como oyente, no habría
problema. Sin embargo, es necesario que te concentres en los cursos que son
las que estás tomando en la maestría, por supuesto.

Saludos
David

**Comment by FavioVazquez** [comment]
Ah entiendo, muchas gracias por responder. ¿Y cuándo abrirá algún curso para la maestría?

**Comment by dpsanders** [comment]
Hola:

Estaré de sabático fuera del país el año que entra, así que estaré dando
curso hasta el año 2017.

Saludos
David

On Sat, Aug 15, 2015 at 5:37 PM, Favio André Vázquez <
notifications@github.com> wrote:

> Ah entiendo, muchas gracias por responder. ¿Y cuándo abrirá algún curso
> para la maestría?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dpsanders/fisica_computacional/issues/1#issuecomment-131458897
> .

## 

Dr. David P. Sanders

Profesor Titular "B" / Associate Professor
Departamento de Física, Facultad de Ciencias
Universidad Nacional Autónoma de México (UNAM)

dpsanders@g dpsanders@ciencias.unam.mxmail.com / Twitter: @DavidPSanders
https://twitter.com/DavidPSanders
http://sistemas.fciencias.unam.mx/~dsanders / GitHub: dpsanders
https://github.com/dpsanders

Cubículo / office: #414, 4o. piso del Depto. de Física

Tel.: (+52 55) 5622 4965
